import assert from 'node:assert/strict';
import { defaultServices, mergeServiceCatalogue, snapshotService, validateService } from '../../utils/serviceCatalogue';
import { normalizeLines } from '../../services/financeDocuments';
import { generateFinanceDocument } from '../../utils/financeDocumentGenerator';
import { buildAccountingEntries, MAKERLAB_ACCOUNTING_TEMPLATE } from '../../utils/accountingExport';
import type { AppSettings, FinanceDocument } from '../../types';

const services = defaultServices('org-test');
assert.equal(services.length, 8);
assert.equal(new Set(services.map(service => service.id)).size, 8);
assert(services.every(service => service.unitPrice === null));
assert.equal(mergeServiceCatalogue('org-test', [{ ...services[0], status: 'archived', version: 1 }, { ...services[1], organizationId: 'other', name: 'Secret' }]).filter(service => service.status === 'active').length, 7);
const source = { ...services[0], unitPrice: 10.33 };
const line = snapshotService(source, 'org-test');
source.name = 'Changed later'; source.description = 'Changed details'; source.unitPrice = 99;
assert.equal(line.description, 'AI Content Studio');
assert.equal(line.unitPrice, 10.33);
assert.throws(() => snapshotService({ ...source, status: 'archived' }, 'org-test'));
assert.throws(() => snapshotService(source, 'other'));
assert.throws(() => validateService({ ...source, unitPrice: NaN }));
assert.throws(() => validateService({ ...source, taxRate: 101 }));
assert.throws(() => validateService({ ...source, quantity: 0 }));
assert.throws(() => validateService({ ...source, name: ' ' }));
assert(!('id' in validateService(source)), 'write whitelist strips metadata');
for (const value of [NaN, Infinity, -1, 0]) assert.throws(() => normalizeLines([{ ...line, unitPrice: value }]));
assert.throws(() => normalizeLines([{ ...line, taxRate: 101 }]));
const normalized = normalizeLines([{ ...line, description: 'Edited <script>', details: 'Custom <img>\nSecond line', quantity: 3, unitPrice: 0.335, taxRate: 20 }]);
assert.equal(normalized[0].subtotal, 1.02);
assert.equal(normalized[0].taxAmount, 0.2);
assert.equal(normalized[0].total, 1.22);
assert.equal(normalized[0].serviceName, 'AI Content Studio');
const record: FinanceDocument = { id: 'one', organizationId: 'org-test', kind: 'invoice', number: '2026S001', sequenceYear: 2026, sequenceNumber: 1, sequenceType: 'service', issueDate: '2026-09-09', dueDate: '2026-09-30', status: 'issued', currency: 'MAD', customer: { type: 'company', name: 'Client' }, participants: [], lines: normalized, subtotal: 1.02, taxAmount: 0.2, total: 1.22 };
let html = '';
(globalThis as any).window = { open: () => ({ document: { write: (value: string) => { html = value; }, close() {} } }) };
generateFinanceDocument(record, { academyName: 'Test' } as AppSettings, { preview: true });
assert(html.includes('Document non émis'));
assert(html.includes('Custom &lt;img&gt;\nSecond line'));
assert(!html.includes('<script>'));
generateFinanceDocument(record, { academyName: 'Test' } as AppSettings);
assert(html.includes('2026S001'));
assert(!html.includes('Document non émis'));
assert(!html.includes('Document comptable'));
assert(!html.includes('Échéance'));
const entries = buildAccountingEntries([record], MAKERLAB_ACCOUNTING_TEMPLATE);
assert.equal(Math.abs(Math.round(entries.reduce((sum, entry) => sum + entry.debit - entry.credit, 0) * 100)), 0);
console.log('Service catalogue domain/snapshot/totals/print/export checks passed.');
