import assert from 'node:assert/strict';
import type { ProjectTemplate, StudentProject } from '../types.ts';
import { learnerDirectory, learnerWorkspace, buildProfileAssignmentPatch } from './instructorLearner.ts';
import { missionIsVisibleToLearner } from './missionAssignment.ts';
import { getMissionReadiness, getMissionSavePolicy } from './missionContent.ts';
let checks = 0;
const equal = (actual: unknown, expected: unknown) => { assert.deepEqual(actual, expected); checks++; };
const rejects = (action: () => unknown, message: RegExp) => { assert.throws(action, message); checks++; };
const org = 'org-a';
const year = '2026-2027';
const profile = { id: 'record-a', _source: 'student_profile', organizationId: org, name: 'Same name', loginInfo: { uid: 'auth-a' } };
const project = (id: string, studentId = 'record-a', academicYearId = year): StudentProject => ({ id, title: id, studentId, organizationId: org, academicYearId, status: 'building', steps: [], skills: [], resources: [], commits: [] } as StudentProject);
const proof = { ...project('proof', 'auth-a'), steps: [{ id: 'test', title: 'Test', status: 'PENDING_REVIEW' as const, submittedAt: '2026-10-01T11:00:00Z' }], reviewHistory: [{ id: 'decision', outcome: 'step_changes_requested' as const, reviewedAt: '2026-09-29T10:00:00Z', feedback: 'Repeat test.' }] };
const old = { ...project('old', 'record-a', '2025-2026'), steps: [{ id: '1', title: 'Plan', status: 'done' as const }, { id: '2', title: 'Build', status: 'todo' as const }] };
const published = { ...project('published'), status: 'published' as const, reviewHistory: [{ id: 'publish', outcome: 'published' as const, reviewedAt: '2026-10-01T10:00:00Z', feedback: 'Great build.' }] };
const builds = [proof, old, published, project('other', 'record-b'), { ...project('foreign'), organizationId: 'org-b' }];
const students = [profile, { id: 'record-b', organizationId: org, name: 'Same name', _source: 'student_profile' }, { ...profile, id: 'foreign-record', organizationId: 'org-b' }, { id: 'teacher', role: 'instructor', organizationId: org }];
const directory = learnerDirectory(students, builds, org);
equal(directory.length, 2);
equal(directory[0].id, 'record-a');
equal(directory[0].ownerIds, ['record-a', 'auth-a']);
equal(directory[0].projectCount, 3);
equal(directory[0].reviewCount, 1);
equal(directory[0].publishedCount, 1);
equal(directory[1].projectCount, 1);
equal(learnerDirectory(students, builds, '').length, 0);
equal(learnerDirectory(students, builds, 'org-b')[0].projectCount, 0);
equal(learnerDirectory([{ ...profile, status: 'inactive' }], builds, org)[0].assignable, false);
const ambiguous = learnerDirectory([profile, { ...profile, id: 'record-duplicate' }], builds, org);
equal(ambiguous.every(item => !item.assignable), true);
equal(ambiguous.find(item => item.id === 'record-a')!.ownerIds, ['record-a']);
equal(ambiguous.flatMap(item => item.projects).some(item => item.id === 'proof'), false);
const mission = (id: string, audience: ProjectTemplate['targetAudience'] = { grades: ['g-a'] }): ProjectTemplate => ({ id, organizationId: org, status: 'assigned', title: id, description: 'Build and test.', station: 'Circuits', targetAudience: audience } as ProjectTemplate);
const catalog = [mission('class', { programs: ['STEM'], grades: ['Mini Makers'], groups: ['Crew 5'] }), mission('other'), mission('direct', { students: ['auth-a'] }), { ...mission('foreign'), organizationId: 'org-b' }, { ...mission('draft'), status: 'draft' as const }];
const enrollments = [{ id: 'active', studentId: 'record-a', organizationId: org, status: 'active', programId: 'p', gradeId: 'g', groupId: 'crew' }, { id: 'inactive', studentId: 'record-a', organizationId: org, status: 'inactive', gradeId: 'g-a' }, { id: 'foreign', studentId: 'record-a', organizationId: 'org-b', status: 'active', gradeId: 'g-a' }];
const programs = [{ id: 'p', organizationId: org, name: 'STEM', grades: [{ id: 'g', name: 'Mini Makers', groups: [{ id: 'crew', name: 'Crew 5' }] }] }];
const desk = learnerWorkspace(directory[0], catalog, enrollments, programs, org, year);
equal(desk.current.length, 2); equal(desk.archived.length, 1);
equal(desk.missions.map(item => item.mission.id), ['class', 'direct']);
equal(desk.missions.map(item => item.direct), [false, true]);
equal(desk.placements[0], { id: 'active', program: 'STEM', grade: 'Mini Makers', group: 'Crew 5' });
equal(desk.history.map(item => item.review.id), ['publish', 'decision']);
equal(desk.reviews.map(item => item.id), ['proof']);
equal(learnerWorkspace(directory[0], catalog, [], programs, org, year).missions.map(item => item.mission.id), ['direct']);
const baseline = mission('add', { programs: ['p'], grades: ['g-a'], groups: ['outside'], students: [], additionalStudents: ['record-b'] });
const untouched = JSON.stringify(baseline);
const patch = buildProfileAssignmentPatch(baseline, 'record-a', org);
equal(patch.targetAudience?.additionalStudents, ['record-b', 'record-a']);
equal(patch.targetAudience?.groups, ['outside']); equal(patch.targetAudience?.grades, ['g-a']);
equal(JSON.stringify(baseline), untouched);
equal(buildProfileAssignmentPatch({ ...baseline, ...patch }, 'record-a', org), {});
equal(buildProfileAssignmentPatch(mission('individual', { students: ['record-a'] }), 'record-a', org), {});
equal(buildProfileAssignmentPatch({ ...baseline, status: 'featured' }, 'record-a', org).status, 'featured');
const context = { ownerIds: ['record-a'], programIds: [], gradeIds: [], groupIds: [] };
equal(missionIsVisibleToLearner({ ...baseline, ...patch }, context), true);
equal(missionIsVisibleToLearner(baseline, context), false);
equal(missionIsVisibleToLearner({ ...baseline, ...patch }, { ...context, ownerIds: ['record-b'] }), true);
equal(missionIsVisibleToLearner({ ...baseline, ...patch }, { ownerIds: ['class-student'], programIds: ['p'], gradeIds: ['g-a'], groupIds: ['outside'] }), true);
const draft = { ...mission('ready', {}), status: 'draft' as const, defaultWorkflowId: 'engineering', missionBrief: { goal: 'Test a device', finalOutcome: 'Working prototype' } };
equal(buildProfileAssignmentPatch(draft, 'record-a', org).status, 'assigned');
equal(getMissionReadiness({ ...draft, ...buildProfileAssignmentPatch(draft, 'record-a', org) }).publishReady, true);
equal(getMissionSavePolicy({ ...draft, ...buildProfileAssignmentPatch(draft, 'record-a', org) }).removedExistingAudience, false);
rejects(() => buildProfileAssignmentPatch({ ...draft, targetAudience: { grades: ['g-a'] } }, 'record-a', org), /planned audience/);
rejects(() => buildProfileAssignmentPatch({ ...draft, defaultWorkflowId: undefined }, 'record-a', org), /Complete/);
rejects(() => buildProfileAssignmentPatch({ ...baseline, status: 'archived' }, 'record-a', org), /Archived/);
rejects(() => buildProfileAssignmentPatch(baseline, 'record-a', 'org-b'), /organization/);
rejects(() => buildProfileAssignmentPatch(baseline, '', org), /organization/);
console.log(`Instructor learner workspace smoke: ${checks} assertions passed.`);
