import assert from 'node:assert/strict';
import { fieldLogYears, isVerifiedOwnedProject, projectLane, projectProgress, selectFieldLog, selectWorkbench, workbenchStorageKey } from './learnerWorkbench.ts';
import type { StudentProject } from '../types.ts';

const year = '2026-2027';
const make = (id: string, status: string, academicYearId = year, seconds = 0): StudentProject => ({ id, status, academicYearId, updatedAt: { seconds }, organizationId: 'org-a', studentId: 'student-a', title: id, station: 'Circuits', steps: [], skills: [], resources: [], commits: [] } as unknown as StudentProject);
const projects = [make('older-build', 'building', year, 20), make('latest-build', 'testing', year, 30), make('published', 'published', year, 40), make('feedback', 'changes_requested', year, 10), make('review', 'submitted', year, 50), make('old', 'building', '2025-2026', 100), make('legacy', 'IN_PROGRESS', year, 5)];
assert.equal(selectWorkbench(projects, year).pinned?.id, 'latest-build');
assert.equal(selectWorkbench(projects, year, 'older-build').pinned?.id, 'older-build');
assert.equal(selectWorkbench(projects, year, 'published').pinned?.id, 'latest-build');
assert.equal(selectWorkbench(projects, year, 'old').pinned?.id, 'latest-build');
const selection = selectWorkbench(projects, year, 'older-build');
assert.deepEqual(selection.others.map(project => project.id), ['latest-build', 'legacy']);
assert.deepEqual(selection.instructor.map(project => project.id), ['feedback', 'review']);
assert.equal(selectWorkbench([make('review', 'PENDING_REVIEW')], year).pinned, undefined);
assert.equal(projectLane('DONE'), 'finished');
assert.equal(projectLane('unknown'), 'other');
assert.equal(projectProgress(make('blank', 'planning')).percent, 0);
assert.equal(projectProgress({ ...make('steps', 'building'), steps: [{ id: '1', title: 'Plan', status: 'done' }, { id: '2', title: 'Wire', status: 'doing' }, { id: '3', title: 'Test', status: 'todo' }] }).next, 'Wire');
assert.deepEqual(fieldLogYears(projects, year), ['2025-2026']);
assert.deepEqual(selectFieldLog(projects, year, 'previous', '2025-2026').map(project => project.id), ['old']);
assert.deepEqual(selectFieldLog(projects, year, 'current', '').map(project => project.id), ['review', 'published', 'feedback']);
assert.equal(isVerifiedOwnedProject(make('own', 'building'), 'org-a', ['student-a']), true);
assert.equal(isVerifiedOwnedProject(make('foreign-org', 'building'), 'org-b', ['student-a']), false);
assert.equal(isVerifiedOwnedProject(make('foreign-owner', 'building'), 'org-a', ['student-b']), false);
assert.equal(isVerifiedOwnedProject({ ...make('alias', 'building'), studentId: 'linked-auth' }, 'org-a', ['student-a', 'linked-auth']), true);
assert.notEqual(workbenchStorageKey('org-a', 'student-a'), workbenchStorageKey('org-a', 'student-b'));
assert.notEqual(workbenchStorageKey('org-a', 'student-a'), workbenchStorageKey('org-b', 'student-a'));
assert.equal(workbenchStorageKey(undefined, 'student-a'), null);
assert.deepEqual(projects.map(project => project.id), ['older-build', 'latest-build', 'published', 'feedback', 'review', 'old', 'legacy']);
console.log('Learner workbench smoke: 22 assertions passed.');
