import assert from 'node:assert/strict';
import { normalizeImportRow, importTasks, materializeImport, importDocumentId, resolveReference, sampleImportRow, type ImportCatalog } from './missionImport.ts';

const catalog: ImportCatalog = { stations: [{ id: 'circuits', label: 'Circuits' }], workflows: [], programs: [{ id: 'stem', label: 'STEMQuest' }], grades: [{ id: 'g5', label: 'Grade 5', programId: 'stem' }], groups: [{ id: 'Wednesday', label: 'Wednesday', gradeId: 'g5', programId: 'stem' }], students: [{ id: 'student-1', label: 'Aya', aliases: ['auth-1'] }] };
const row = { ...sampleImportRow, CoverFile: '', ResourcesJSON: '[]', AudiencePrograms: 'STEMQuest', AudienceGrades: 'Grade 5', AudienceStudents: 'auth-1' };
const complete = normalizeImportRow(row, 2, catalog);
assert.deepEqual(complete.errors, []);
assert.deepEqual(complete.questions, []);
assert.deepEqual(importTasks(complete, catalog), []);
assert.equal(complete.mission.station, 'circuits');
assert.deepEqual(complete.mission.targetAudience?.students, ['student-1']);
assert.equal(complete.workflow?.phases[1].evidenceRequirements?.[0].type, 'video');
assert.equal(materializeImport(complete, catalog).mission.status, 'draft');
const assets = normalizeImportRow({ ...row, CoverFile: 'cover.png', ResourcesJSON: JSON.stringify([{ id: 'guide', title: 'Guide', type: 'file', fileName: 'guide.pdf' }]), StepResourcesJSON: JSON.stringify({ 'phase-1': [{ id: 'plan', title: 'Plan', type: 'file', fileName: 'plan.pdf' }] }) }, 2, catalog);
assert.equal(assets.assets.length, 3);
assert.throws(() => materializeImport(assets, catalog), /Upload/);
assets.assets.forEach(a => { a.url = `https://example.com/${a.fileName}`; });
const payload = materializeImport(assets, catalog);
assert.equal(payload.mission.thumbnailUrl, 'https://example.com/cover.png');
assert.equal(payload.mission.resources?.[0].url, 'https://example.com/guide.pdf');
assert.equal(payload.mission.stepResources?.['phase-1'][0].url, 'https://example.com/plan.pdf');
assets.assets.forEach(a => { a.url = undefined; a.skipped = true; });
assert.deepEqual(materializeImport(assets, catalog).mission.resources, []);
for (const date of ['2026-13-01', '2026-02-31', 'nonsense']) assert.ok(normalizeImportRow({ ...row, DueDate: date }, 2, catalog).errors.some(e => e.field === 'DueDate'));
assert.equal(normalizeImportRow({ ...row, DueDate: '2026-10-01' }, 2, catalog).dueDate, '2026-10-01');
const bad = normalizeImportRow({ ...row, DeliverablesJSON: '{oops', Difficulty: 'expert', ResourcesJSON: JSON.stringify([{ title: 'Bad link', url: 'javascript:alert(1)' }]) }, 2, catalog);
assert.ok(bad.errors.length >= 3);
assert.throws(() => materializeImport(bad, catalog), /Resolve CSV/);
assert.equal(resolveReference('Grade 5', [{ id: 'g1', label: 'Grade 5' }, { id: 'g2', label: 'Grade 5' }]), undefined);
assert.equal(resolveReference('Aya', catalog.students, true), undefined);
assert.ok(normalizeImportRow({ ...row, AudienceStudents: 'Aya' }, 2, catalog).questions.some(q => q.field === 'students'));
const resourcePhase = normalizeImportRow({ ...row, StepResourcesJSON: JSON.stringify({ unknown: [{ title: 'Guide', url: 'https://example.com/guide' }] }) }, 2, catalog);
assert.throws(() => materializeImport(resourcePhase, catalog), /phase ID/);
const custom = normalizeImportRow({ ...row, WorkflowPhasesJSON: JSON.stringify([{ id: 'one', name: 'Build', checklist: ['Wire'], evidenceRequirements: [{ type: 'document', prompt: 'Upload the report', required: false }], resources: [{ title: 'Guide', fileName: 'guide.pdf' }] }]) }, 2, catalog);
assert.equal(custom.workflow?.phases[0].evidenceRequirements?.[0].required, false);
assert.equal(custom.assets[0].phaseId, 'one');
custom.assets[0].url = 'https://example.com/guide.pdf';
assert.equal(materializeImport(custom, catalog).workflow?.phases[0].resources?.[0].url, 'https://example.com/guide.pdf');
custom.workflow!.phases[0].evidenceRequirements![0].prompt = '';
assert.throws(() => materializeImport(custom, catalog), /evidence prompt/);
const legacy = normalizeImportRow({ Title: 'Legacy', Description: 'Description', Station: 'Circuits', Outcome_1_Title: 'Learn', Outcome_1_Desc: 'Outcome', RealWorld_Companies: 'NASA,Arduino', Technologies: 'Python,Sensors' }, 2, catalog);
assert.equal(legacy.mission.learningOutcomes?.[0].title, 'Learn');
assert.equal(legacy.mission.realWorldApp?.companies.length, 2);
assert.equal(legacy.mission.technologies?.length, 2);
const id = await importDocumentId('org', 'plant-v1');
assert.equal(id, await importDocumentId('org', 'plant-v1'));
assert.notEqual(id, await importDocumentId('other-org', 'plant-v1'));
assert.notEqual(id, await importDocumentId('org', 'plant-v2'));
console.log('Mission import smoke passed: full content, friendly/JSON phases, asset binding/removal, dates, unsafe URLs, ambiguity, canonical learners, legacy CSV, tenant-scoped repeat keys.');
