import assert from 'node:assert/strict';
import { buildReviewPatch, currentStepReview, effectiveStepReviewStatus, learnerSaveFingerprint, needsReview, pendingProofCount, proofKind, reviewFingerprint, reviewQueue, safeProofUrl, stepIsApproved, stepReviewFeedback, submittedProof } from './projectReview.ts';
import type { StudentProject } from '../types.ts';

const actor = { uid: 'teacher', role: 'instructor', organizationId: 'org-a', name: 'Mentor' };
const base: StudentProject = { id: 'p1', studentId: 's1', organizationId: 'org-a', title: 'Plant guardian', description: 'Test a sensor', status: 'building', station: 'Circuits', reviewProtocolVersion: 1, commits: [], resources: [], skills: [], steps: [{ id: 'test', title: 'Wet/dry test', status: 'PENDING_REVIEW', required: true, evidence: 'https://files.test/test.jpg?token=secret', note: 'First reading', submittedAt: '2026-10-01T10:00:00Z' }] };
let assertions = 0;
const check = (test: () => void) => { test(); assertions++; };
const command = (project: StudentProject, outcome: any, stepId?: string, feedback = '') => ({ id: `decision-${assertions}`, outcome, stepId, feedback, expectedFingerprint: reviewFingerprint(project, stepId) });
check(() => assert.equal(needsReview(base), true));
check(() => assert.equal(pendingProofCount(base), 1));
check(() => assert.equal(needsReview({ ...base, steps: [], status: 'submitted' }), true));
check(() => assert.equal(needsReview({ ...base, steps: [], status: 'published' }), false));
check(() => assert.deepEqual(reviewQueue([{ ...base, id: 'old', steps: [{ ...base.steps[0], submittedAt: '2026-09-30' }] }, base]).map(item => item.project.id), ['p1', 'old']));
check(() => assert.equal(reviewQueue([{ ...base, steps: [{ ...base.steps[0], status: 'pending-review' as any }] }]).length, 1));
check(() => assert.equal(reviewQueue([{ ...base, steps: [], status: 'submitted', updatedAt: { seconds: 10 } as any }])[0].submittedAt, 10000));
check(() => assert.equal(proofKind('https://firebasestorage.googleapis.com/v0/b/x/o/student%2Fproof.JPG?alt=media&token=x'), 'image'));
check(() => assert.equal(proofKind('https://files.test/proof.mp4?token=x'), 'video'));
check(() => assert.equal(proofKind('https://files.test/no-extension', 'audio/mpeg'), 'audio'));
check(() => assert.equal(proofKind('https://files.test/proof.pdf?token=x'), 'pdf'));
check(() => assert.equal(safeProofUrl('javascript:alert(1)'), null));
check(() => assert.equal(safeProofUrl('data:text/html;base64,abc'), null));
check(() => assert.equal(safeProofUrl('data:image/svg+xml;base64,abc'), null));
check(() => assert.equal(safeProofUrl('data:image/png;base64,abc'), 'data:image/png;base64,abc'));
check(() => assert.equal(safeProofUrl('https://files.test/proof.jpg'), 'https://files.test/proof.jpg'));
const rejectCommand = command(base, 'step_changes_requested', 'test', 'Label both readings.');
const rejected = { ...base, ...buildReviewPatch(base, rejectCommand, actor, '2026-10-01T11:00:00Z') };
check(() => assert.equal(rejected.steps[0].status, 'REJECTED'));
check(() => assert.equal(rejected.steps[0].reviewNotes, 'Label both readings.'));
check(() => assert.equal(rejected.reviewHistory?.[0].submission?.note, 'First reading'));
check(() => assert.equal(currentStepReview(rejected, rejected.steps[0])?.outcome, 'step_changes_requested'));
check(() => assert.equal(effectiveStepReviewStatus(rejected, rejected.steps[0]), 'rejected'));
check(() => assert.equal(stepReviewFeedback(rejected, rejected.steps[0]), 'Label both readings.'));
check(() => assert.equal(needsReview(rejected), false));
const forgedApprovedStep = { ...rejected, status: 'submitted' as const, steps: [{ ...rejected.steps[0], status: 'done' as const, reviewNotes: 'Self approved' }] };
check(() => assert.equal(effectiveStepReviewStatus(forgedApprovedStep, forgedApprovedStep.steps[0]), 'rejected'));
check(() => assert.equal(stepReviewFeedback(forgedApprovedStep, forgedApprovedStep.steps[0]), 'Label both readings.'));
check(() => assert.throws(() => buildReviewPatch(forgedApprovedStep, command(forgedApprovedStep, 'published'), actor, 'now'), /required step/));
check(() => assert.deepEqual(buildReviewPatch(rejected, rejectCommand, actor, 'later'), {}));
check(() => assert.throws(() => buildReviewPatch(base, command(base, 'step_changes_requested', 'test'), actor, 'now'), /clear next action/));
check(() => assert.throws(() => buildReviewPatch(base, command(base, 'step_approved', 'test'), { ...actor, role: 'student' }, 'now'), /cannot review/));
check(() => assert.throws(() => buildReviewPatch(base, command(base, 'step_approved', 'test'), { ...actor, organizationId: 'org-b' }, 'now'), /cannot review/));
check(() => assert.throws(() => buildReviewPatch({ ...base, steps: [{ ...base.steps[0], note: 'New proof' }] }, command(base, 'step_approved', 'test'), actor, 'now'), /changed/));
const resubmitted = { ...rejected, steps: [submittedProof(rejected.steps[0], 'https://files.test/v2.jpg', 'Both readings labelled', '2026-10-01T12:00:00Z', 'image/jpeg')] };
check(() => assert.equal(resubmitted.steps[0].submissionHistory?.length, 2));
check(() => assert.equal(resubmitted.steps[0].submissionHistory?.[0].note, 'First reading'));
check(() => assert.equal(resubmitted.reviewHistory?.[0].feedback, 'Label both readings.'));
check(() => assert.equal(effectiveStepReviewStatus(resubmitted, resubmitted.steps[0]), 'pending_review'));
check(() => assert.equal(needsReview(resubmitted), true));
const approved = { ...resubmitted, ...buildReviewPatch(resubmitted, command(resubmitted, 'step_approved', 'test', 'Clear evidence.'), actor, '2026-10-01T13:00:00Z') };
check(() => assert.equal(approved.steps[0].status, 'done'));
check(() => assert.equal(approved.reviewHistory?.length, 2));
check(() => assert.equal(stepIsApproved(approved, approved.steps[0]), true));
const changedAfterApproval = { ...approved, steps: [{ ...approved.steps[0], note: 'Changed after approval', status: 'done' as const }] };
check(() => assert.equal(stepIsApproved(changedAfterApproval, changedAfterApproval.steps[0]), false));
check(() => assert.equal(effectiveStepReviewStatus(changedAfterApproval, changedAfterApproval.steps[0]), 'pending_review'));
check(() => assert.equal(stepReviewFeedback(changedAfterApproval, changedAfterApproval.steps[0]), ''));
check(() => assert.equal(reviewQueue([changedAfterApproval]).length, 1));
const final = { ...approved, status: 'submitted' as const, mediaUrls: ['https://files.test/final.jpg'] };
const publishCommand = { ...command(final, 'published'), xp: 50 };
const published = { ...final, ...buildReviewPatch(final, publishCommand, actor, '2026-10-01T14:00:00Z') };
check(() => assert.equal(published.status, 'published'));
check(() => assert.equal(published.xpReward, 50));
check(() => assert.equal(published.reviewHistory?.length, 3));
check(() => assert.deepEqual(buildReviewPatch(published, publishCommand, actor, 'later'), {}));
check(() => assert.throws(() => buildReviewPatch({ ...base, status: 'submitted' }, command({ ...base, status: 'submitted' }, 'published'), actor, 'now'), /required step/));
check(() => assert.throws(() => buildReviewPatch(final, { ...publishCommand, xp: -1 }, actor, 'now'), /whole number/));
check(() => assert.equal(learnerSaveFingerprint(base), learnerSaveFingerprint({ ...base, steps: [{ note: base.steps[0].note, ...base.steps[0] }] })));
check(() => assert.notEqual(learnerSaveFingerprint(base), learnerSaveFingerprint(rejected)));
check(() => assert.equal(published.reviewHistory?.[0].submission?.note, 'First reading'));
check(() => assert.equal(reviewQueue([{ ...base, steps: [{ ...base.steps[0], id: 'old', submittedAt: '2026-09-30' }, { ...base.steps[0], id: 'new' }] }])[0].pendingSteps[0].id, 'new'));
check(() => assert.throws(() => buildReviewPatch(base, command(base, 'unknown', 'test'), actor, 'now'), /valid review/));
check(() => assert.equal(submittedProof({ ...base.steps[0], evidenceMimeType: 'image/jpeg' }, base.steps[0].evidence!, 'New note', 'now').evidenceMimeType, 'image/jpeg'));
check(() => assert.equal(learnerSaveFingerprint({ ...base, dueDate: new Date(1000) }), learnerSaveFingerprint({ ...base, dueDate: { toMillis: () => 1000 } as any })));
check(() => assert.notEqual(learnerSaveFingerprint(base), learnerSaveFingerprint({ ...base, commits: [{ id: 'commit', message: 'New work', timestamp: new Date() }] })));
check(() => assert.equal(buildReviewPatch({ ...final, steps: [{ ...final.steps[0], required: false, status: 'todo' }] }, command({ ...final, steps: [{ ...final.steps[0], required: false, status: 'todo' }] }, 'published'), actor, 'now').status, 'published'));
const legacyFinal = { ...final, reviewProtocolVersion: undefined, stepReviews: undefined, reviewHistory: [], steps: [{ ...final.steps[0], status: 'done' as const }], status: 'submitted' as const };
check(() => assert.equal(buildReviewPatch(legacyFinal, command(legacyFinal, 'published'), actor, 'now').status, 'published'));
console.log(`Project review smoke passed: ${assertions} assertions.`);
